### ISSUE TITLE
Base Fork of VSCodeRibbon off of Eclipse Theia instead of VSCode?

### ISSUE THREAD

**Issue by sahil48** [CodeRibbon/VSCodeRibbon#22]
Since VSCodeRibbon is going to be a fork of VSCode, I am not sure if Eclipse Theia had any benefits over VSCode by nature of being more extendible, at least as described on the website, and largely based on VSCode. Thought I'm bring this up if it is of any value. https://theia-ide.org/

**Comment by robobenklein** [comment]
Awesome, I quite like the development direction there, though I have little familiarity with either codebase to make a good judgment yet.

Do you know if there's any plugin API difference or extensibility method that allows access to the main workspace? (e.g. CodeRibbon needs to replace the whole center workspace to render the ribbon)

I would like to do VSCodeRibbon as a plugin, but that simply isn't possible with the current extension API.

**Comment by sahil48** [comment]
I'm less technically inclined in this regards. 😅 

Some API Articles and Documentations is below. Hope this helps in reaching an optimal decision.

* https://eclipsesource.com/blogs/2020/05/04/how-to-create-develop-an-eclipse-theia-ide-plugin/
* https://theia-ide.org/docs/authoring_plugins
* https://eclipse-theia.github.io/theia/docs/next/modules/editor.html

There is also a discussion group where you may be able to get better information: https://community.theia-ide.org/

**Comment by sahil48** [comment]
Some applications made with Theia are here: https://blogs.eclipse.org/post/brian-king/eclipse-theia-builds-momentum

**Comment by robobenklein** [comment]
Done. Theia implementation is far enough along I'm not going back on that decision anytime soon.

https://github.com/CodeRibbon/CodeRibbon-Theia

**Comment by sahil48** [comment]
Congratulations! Glad the information was helpful and look forward to try out the new CodeRibbon when it is ready.
