### ISSUE TITLE
Fast-build or Live-Run edit mode

### ISSUE THREAD

**Issue by robobenklein** [CodeRibbon/VSCodeRibbon#6]
Need to find a method for testing changes without having to wait 5 minutes for a build of the entire vscode to complete.

Atom had a 'development` mode switch that would live reload packages and the editor could be reloaded with a hotkey, not a clue how to do something similar with VSCode.

**Comment by solsane** [comment]
There's something similar for VSCode. The guide refers to the [Extension Development Host](https://code.visualstudio.com/api/get-started/your-first-extension). In the yeoman generated project they use in this guide, in the .vscode directory, they have an action associated with pressing f5 to do this, I don't have the content of it handy but I can post that later or you could replicate it yourself.

**Comment by jtagcat** [comment]
You can reload VSCode with `Ctrl` + `R`, but that probably doesn't work for this use-case.

Alternatively, VSCode can run over the browser, having it on a build server (I can provide for this use) would likely speed it up significantly.

I'd like to think that the upstream already has build caching and optimizations, you might be missing opportunistic binaries or something. Indeed, something to research.

**Comment by robobenklein** [comment]
Done with a browser view of Theia + yarn watching lerna workspaces.
